In [27]:
import cv2
import numpy as np

In [28]:
kernel = cv2.getGaussianKernel(3,3)
kernel


array([[0.32710442],
       [0.34579116],
       [0.32710442]])

In [29]:
patch = np.full((5,5), 100).astype(np.uint8)

blurred = cv2.GaussianBlur(patch,(3,3),5)

In [30]:
print(blurred)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]
